materials:
    default: &MATERIAL_DEFAULT
        # The material name
        name: 'default'
        # The material color in RGBA format
        color:
            r: 0.5
            g: 0.5
            b: 0.5
            a: 1.0
        # The material texture
        texture: ''
    rubber:
        <<: *MATERIAL_DEFAULT
        name: 'rubber'
        color:
            r: 0.9
            g: 0.4
            b: 0.1
            a: 1.0
    plastic:
        <<: *MATERIAL_DEFAULT
        name: 'plastic'
        color:
            r: 0.1
            g: 0.1
            b: 0.9
            a: 1.0
    metal:
        <<: *MATERIAL_DEFAULT
        name: 'metal'
        color:
            r: 0.8
            g: 0.8
            b: 0.8
            a: 1.0


joints:
    default: &JOINT_DEFAULT
        effort: 100
        velocity: 100
        damping: 0.1
        friction: 0.1

objects:
    # base object in case a model is not mapped
    base: # a generic cube of L=0.1m, M=1kg
        joint_type: 'fixed'
        figure: 'box'
        # The sizes of the cuboid in meters
        width: 0.01
        length: 0.01
        height: 0.01
        # visualization properties
        v_origin: # describe the visual origin
            v_x: 0    # x-axis
            v_y: 0    # y-axis
            v_z: 0    # z-axis
            v_roll: 0    # roll
            v_pitch: 0    # pitch
            v_yaw: 0    # yaw
        # The mass in kg
        mass: 0.001
        # The inertial matrix in kg*m^2 [ixx, ixy, ixz, iyy, iyz, izz]
        inertia:
            ixx: 1E-7
            ixy: 0
            ixz: 0
            iyy: 1E-7
            iyz: 0
            izz: 1E-7
            xyz: "0 0 0"
            rpy: "0 0 0"
    wheel:
        # Inherits from the default joint properties
        <<: *JOINT_DEFAULT
        joint_type: 'continuous'
        figure: 'sphere'
        # The wheel radius in meters
        radius: 0.1
        # The wheel length in meters
        length: 0.05
        # visualization properties
        v_origin: # describe the visual origin
            v_x: 0    # x-axis
            v_y: 0    # y-axis
            v_z: 0    # z-axis
            v_roll: 0    # roll
            v_pitch: 0    # pitch
            v_yaw: 0    # yaw
        # The wheel mass in kg
        mass: 1.22
        # The wheel inertial matrix in kg*m^2 [ixx, ixy, ixz, iyy, iyz, izz]
        inertia:
            ixx: 0.0036
            ixy: 0
            ixz: 0
            iyy: 0.0036
            iyz: 0
            izz: 0.0068
            xyz: "0 0 0" #-2.7756E-17 0
            rpy: "0 0 0"

    pivot: # modeled as cuboid with a revolute joint
        # Inherits from the default joint properties
        <<: *JOINT_DEFAULT
        joint_type: 'revolute'
        figure: 'box'
        # bounds of the revolute joint in degrees
        bounds:
            lower: -90
            upper: 90
        # The sizes of the cuboid in meters
        width: 0.13339
        length: 0.1
        height: 0.16504
        # visualization properties
        v_origin: # describe the visual origin
            v_x: -0.017    # x-axis
            v_y: 0    # y-axis
            v_z: -0.08252    # z-axis: -height/2
            v_roll: 0    # roll
            v_pitch: 0    # pitch
            v_yaw: 0    # yaw
        # The pivot mass in kg
        mass: 1.2
        # The pivot inertial matrix in kg*m^2 [ixx, ixy, ixz, iyy, iyz, izz]
        inertia:
            ixx: 0.01
            ixy: 0
            ixz: 0
            iyy: 0.01
            iyz: 0
            izz: 0.01
            xyz: "-0.03 0 -0.04"
            rpy: "0 0 0"
    kart:
        # Inherits from the default joint properties
        <<: *JOINT_DEFAULT
        joint_type: 'fixed'
        figure: 'mesh'
        # The sizes of the cuboid in meters
        width: 0.71
        length: 0.4655
        height: 0.8
        # visualization properties
        v_origin: # describe the visual origin
            v_x: 0    # x-axis
            v_y: 0    # y-axis
            v_z: 0    # z-axis
            v_roll: 0    # roll
            v_pitch: 0    # pitch
            v_yaw: 0    # yaw
        # The kart mass in kg
        mass: 29.552
        # The kart inertial matrix in kg*m^2 [ixx, ixy, ixz, iyy, iyz, izz]
        inertia:
            ixx: 3.674
            ixy: 0
            ixz: -0.0473
            iyy: 4.656
            iyz: 0
            izz: 2.396
            xyz: "0 0 0.34" # offset base_link - C o Mass  is 0.34
            rpy: "0 0 0"
    battery:
        # Inherits from the default joint properties
        <<: *JOINT_DEFAULT
        joint_type: 'fixed'
        figure: 'mesh'
        # The sizes of the cuboid in meters
        width: 0.32
        length: 0.541
        height: 0.275
        # visualization properties
        v_origin: # describe the visual origin
            v_x: 0    # x-axis
            v_y: 0    # y-axis
            v_z: 0    # z-axis
            v_roll: 0    # roll
            v_pitch: 0    # pitch
            v_yaw: 0    # yaw
        # The battery mass in kg
        mass: 55.0
        # The battery inertial matrix in kg*m^2 [ixx, ixy, ixz, iyy, iyz, izz]
        inertia:
            ixx: 0.8143
            ixy: 0
            ixz: 0.0014
            iyy: 1.696
            iyz: 0
            izz: 1.819
            xyz: "0 0 0"
            rpy: "0 0 0"
