alias ll='ls -alF' 
alias la='ls -A'
alias l='ls -CF'
alias clc='clear'
alias fzf='fzf --preview "bat --color=always --line-range :500 {}" --bind "enter:become(nano {})"'
alias reload='source ~/.bashrc'
alias build='/ros_ws/.devcontainer/scripts/build.sh'
alias setup='/ros_ws/.devcontainer/scripts/setup.sh'
alias ..='cd ..' 