services:
  ros2_humble:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      tags:
        - latest
      target: app
      args:
        - BASE_DOCKER_IMAGE=osrf/ros:humble-desktop-full
        - WORKSPACE=/ros_ws
    container_name: ros2_humble
    volumes:
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: ../
        target: /ros_ws
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      # uncomment the following line if you want to use the WSLg GUI
      # - type: bind
      #   source: /mnt/wslg
      #   target: /mnt/wslg
      # uncomment to use intel iGPU
      - type: bind
        source: /dev/dri
        target: /dev/dri
    privileged: true
    network_mode: host
    # runtime: nvidia
    ipc: host
    tty: true            
    cap_add:
      - SYS_PTRACE
    group_add:
      - tty
      - audio      
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      - ROS_DOMAIN_ID=1
      - DISPLAY=${DISPLAY}
      #- NVIDIA_DRIVER_CAPABILITIES=all
      #- NVIDIA_VISIBLE_DEVICES=all
      - QT_X11_NO_MITSHM=1
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - PULSE_SERVER=${PULSE_SERVER}
    # Overrides default entrypoint so things don't shut down after the process ends.
    command: sleep infinity
